version: '3.8'

services:

  ceative:

    container_name: ceative-salessite

    build:

      dockerfile: Dockerfile

      context: .

    image: ceative-salessite-image

    ports:

      - "9027:3000"
