name: Build, Push, and Deploy

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ secrets.REGION }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
  LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  ACCOUNT_ID: 423409732955


jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-image-tag.outputs.IMAGE_TAG }}


    steps:
      - uses: actions/checkout@v3

      - name: Set IMAGE_TAG
        id: set-image-tag
        run: |
          IMAGE_TAG=$(echo "${GITHUB_REF#refs/heads/}" | tr / -)-$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "${IMAGE_TAG}" > image_tag.txt

      - name: Upload IMAGE_TAG
        uses: actions/upload-artifact@v2
        with:
          name: image-tag
          path: image_tag.txt


      - name: Login to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ env.REGION }}
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com  

      - name: Build Docker image with tag
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/ceative-salesite:${IMAGE_TAG} .

      - name: Push Docker image to ECR
        run: |
          docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/ceative-salesite:${IMAGE_TAG}


  deploy-to-lightsail:
    runs-on: ubuntu-latest
    needs: Build-and-Push
    steps:
      - name: Download IMAGE_TAG
        uses: actions/download-artifact@v2
        with:
          name: image-tag

      - name: Set IMAGE_TAG from artifact
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Debug IMAGE_TAG
        run: echo "IMAGE_TAG is ${{ env.IMAGE_TAG }}"

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/external/CEATIVE-LIMITED-SALESITE-FE-001
            ls
            IMAGE_TAG="${{ env.IMAGE_TAG }}"
            echo "IMAGE_TAG is $IMAGE_TAG"
            sed -i "s|image: '423409732955.dkr.ecr.us-east-1.amazonaws.com/ceative-salesite:.*'|image: '423409732955.dkr.ecr.us-east-1.amazonaws.com/ceative-salesite:${IMAGE_TAG}'|g" docker-compose.yml
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 423409732955.dkr.ecr.us-east-1.amazonaws.com
            docker-compose down
            docker-compose up -d


          